version: 2.0

jobs:
  "build":
    docker:
      - image: circleci/ruby:2.2-node
    steps:
      - checkout
      - run: echo "Hello World"

workflows:
  version: 2
  build:
    jobs:
      - "build"
