version: 2.0

jobs:
  "build":
    docker:
      - image: image: zrlmib/ubuntu-ciitest
    steps:
      - checkout
      - setup_remote_docker
      - echo ${DOCKER_LOGIN} && echo $CIRCLE_BRANCH

workflows:
  version: 2
  build:
    jobs:
      - "build"
