version: 2
jobs:
  build:
    docker:
      - image: ubuntu:bionic

    steps:
      - checkout

      - run:
          name: Looking around
          command: pwd; ls

      - run:
          name: Print the Current Time
          command: date
