version: 2
jobs:
  build:
    docker:
      - image: ubuntu:bionic

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Moin Moin.

      - run:
          name: Print the Current Time
          command: date
