version: 2
jobs:
  build:
    context: zrlmib
    docker:
      - image: zrlmib/ubuntu-ciitest
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "A first hello"
      - run:
          name: Looking around
          command: pwd && ls -laR .
      - run:
          name: Building an image 
          command: docker build -t ci-built-image .
      - run:
          name: Push image
          command: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD && docker tag ci-built-image zrlmib/ci-built-image && docker push zrlmib/ci-built-image

