version: 2
jobs:
  build:
    docker:
      - image: zrlmib/ubuntu-ciitest
    steps:
      - checkout
      - run: echo "A first hello"
      - run:
          name: Looking around
          command: pwd && ls -laR .
      - run:
          name: Building an image
          command: docker build -t ci-built-image .

